### ISSUE TITLE
Make this run on M1 Mac

### ISSUE THREAD

**Issue by gaperez64** [gaperez64/acacia-bonsai#12]

**Comment by gaperez64** [comment]
Got beyond spot now @michaelcadilhac, but it seems my mac's clang does not like gnulib (see attached [error log](https://github.com/gaperez64/acacia-bonsai/files/6458241/errors.txt) for `meson compile`). I'll try to look into this later today.

**Comment by mrudu** [comment]
I face a similar error with `meson compile` (see attached [error-log.txt](https://github.com/gaperez64/acacia-bonsai/files/7464271/error-log.txt))

Details of Laptop:
MacBook Pro (13-inch, 2016)
Operating System: macOS Big Sur (v 11.5.2)
Processor: 2 GHz Dual-Core Intel Core i5
Memory: 8 GB 1867 MHz LPDDR3
Graphics: Intel Iris Graphics 540 1536 MB

**Comment by gaperez64** [comment]
Spent at least 12 hours on this now. GLIB is just not OS X friendly, let's focus on Linux for now...
