### ISSUE TITLE
Hardcoded vector types in some code

### ISSUE THREAD

**Issue by ncharl** [gaperez64/acacia-bonsai#22]
The configuration file has a [line](https://github.com/gaperez64/acacia-bonsai/blob/master/src/configuration.hh#L20) to define the type used in vectors (states in the safety game) which is used in many places such as in the main file [here](https://github.com/gaperez64/acacia-bonsai/blob/master/src/acacia-bonsai.cc#L379), but in some places such as [on this line in k-bounded_safety_aut.hh](https://github.com/gaperez64/acacia-bonsai/blob/master/src/k-bounded_safety_aut.hh#L104), `char` is used instead of `VECTOR_ELT_T` and so if the configuration is changed to `short` for example to allow larger values, this line would not behave correctly. Should this be changed?

**Comment by michaelcadilhac** [comment]
That sounds sensible, yes; go ahead.

**Comment by gaperez64** [comment]
This was resolved when merging #29. Thanks @ncharl !
