### ISSUE TITLE
Global variables about boolean states

### ISSUE THREAD

**Issue by ncharl** [gaperez64/acacia-bonsai#25]
There's [two global variables in `vectors.hh`](https://github.com/gaperez64/acacia-bonsai/blob/master/src/vectors.hh#L6-L14) that have to do with the number of (non)boolean states in the current automaton. These variables have to be set correctly for everything to work, but as they are global variables, this complicates using multiple threads as they'd share the variables. Would there be a convenient way of making these not global? @gaperez64 suggested moving either these variables or a pointer to a thread-specific Configuration struct containing the variables into each instance of a vector.

**Comment by gaperez64** [comment]
The alternative is to do this all with forks and interprocess communication (via pipes?)

Any preference, @michaelcadilhac ?

**Comment by michaelcadilhac** [comment]
So far, I've used forks, not threads, so this is not a problem.  If threads are desired for some reason, `static` can be changed for `thread_local` (https://en.cppreference.com/w/cpp/language/storage_duration).

**Comment by gaperez64** [comment]
Ah yes good ol' pthread local! I think because of the need to return
nontrivial structures to the caller, threads might be easier to use in this
case.

Op di 2 mei 2023 16:18 schreef Michaël Cadilhac ***@***.***>:
