### ISSUE TITLE
input_and_not_crossing_inputs used before assignment

### ISSUE THREAD

**Issue by gaperez64** [gaperez64/acacia-bonsai#3]
[here](https://github.com/gaperez64/acacia-bonsai/blob/c19e520ea1e2b6bce3effa9274e1c8957c6bb828/src/ios_precomputation/fake_vars.hh#L49) you see the variable being compared before it being assigned in the second conjunct

**Comment by michaelcadilhac** [comment]
Correct, I'll fix this; how weird that my gcc does not complain...
