### ISSUE TITLE
Parity game solving

### ISSUE THREAD

**Issue by gaperez64** [gaperez64/acacia-bonsai#45]
We have antichain/downset data structures, spot as a front end to read HOA.

Why don't we implement a parity game solver following the antichain-based algorithm described in Lectures in GT for CStists (Chapter 6, Lemma 6.4)?

**Comment by michaelcadilhac** [comment]
Any reason why Oink/Knor isn't an option?

**Comment by gaperez64** [comment]
I think that might indeed be better for a fair comparison.

Op za 30 dec. 2023 15:53 schreef Michaël Cadilhac ***@***.***

**Comment by michaelcadilhac** [comment]
Implemented as https://github.com/michaelcadilhac/oink/tree/downsets.
