### ISSUE TITLE
Running all tests fails

### ISSUE THREAD

**Issue by gaperez64** [gaperez64/acacia-bonsai#5]
On Fedora, there is an issue when running `meson test`. Even after installing the 32-bit libgcc (which seems to be the issue at first), the problem is still there. The error is shown below:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/gaperez/GIT-repos/acacia-bonsai/builddir/tests/check-real-correct.sh'
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
libgcc_s.so.1 must be installed for pthread_cancel to work
```

I am able to run individual tests though, like `meson test antichains`.

**Comment by michaelcadilhac** [comment]
Very much unclear why the script is not built; I'd expect that there's an error before that in meson build.

**Comment by gaperez64** [comment]
It seems to be because of check-real-correct.sh mentioning zsh in the header and me running bash, any idea on how to make this more portable?

**Comment by gaperez64** [comment]
I am going with `#!/usr/bin/env sh -f` to support any Bourne-shell derivative ;) let me know if that works for you on zsh and then we close this.

**Comment by gaperez64** [comment]
Even better! `#!/usr/bin/env zsh -f` works after installing zsh so I'll just do that and mention it in the readme.
