### ISSUE TITLE
Pygraph is not python3 friendly

### ISSUE THREAD

**Issue by gaperez64** [gaperez64/acacia-bonsai#7]
I have installed pygraph manually via `pip3 install pygraph`. However, it's an old package which seems to be for python2 rather, so when running the tests for acacia+ (since we do so with python3) it keeps giving warning about exceptions not being in the right format.

**Comment by michaelcadilhac** [comment]
`pip3 install --upgrade git+https://github.com/jciskey/pygraph`

**Comment by gaperez64** [comment]
Still getting problems, but different ones:

```
[ltl/realizable/ltl2dba_C2_2.ltl] FAILED: FALSE NEGATIVE (may happen if K is too small)
--- stderr ---
[ltl/realizable/ltl2dba_C2_2.ltl] Traceback (most recent call last):
[ltl/realizable/ltl2dba_C2_2.ltl]   File "/home/gaperez/GIT-repos/acacia-bonsai/tests/acacia-plus/acacia_plus.py", line 28, in <module>
[ltl/realizable/ltl2dba_C2_2.ltl]     from pygraph.classes.digraph import digraph
[ltl/realizable/ltl2dba_C2_2.ltl] ModuleNotFoundError: No module named 'pygraph.classes.digraph'
```

**Comment by gaperez64** [comment]
We installed Shoobx's version by hand and it works.
