### ISSUE TITLE
kdtree enters an infinite loop

### ISSUE THREAD

**Issue by michaelcadilhac** [gaperez64/acacia-bonsai#9]
On the test `ab/ltl2dba_theta_2.ltl`, this call:

```
        if (not found) {
          // this dimension is useless, move to the next one
          return recursive_build (sorted, depth + 1);
        }
```

results in an infinite loop.  Funnily enough, this seems to depend on the optimization flags: some _more_ tests fail with `-O3`.

**Comment by gaperez64** [comment]
interesting! will take a look later today

**Comment by gaperez64** [comment]
I am unable to reproduce this @michaelcadilhac , which buildtype are you using with meson to get this?

**Comment by gaperez64** [comment]
I found a possible infinite loop in the logic though, pushed a change now, let me know if the problem persists.

**Comment by gaperez64** [comment]
It was a bug in your code (array_backed).
